Bug Fixes (#18)
* Fixed IllegalArgumentException that was throw during ImportFromJsonAction
* Fixed NullPointerException that was throw during FlintRunnerTool > run
* Fixes NoClassDefFoundError during generation
* Changed From Using textgen to load model for FlintRunnerTool to using make.